### ISSUE TITLE
kp_winprob Error:

### ISSUE THREAD

**Issue by TrevixNav** [saiemgilani/hoopR#30]
**Error with kp_winprob:**
I am running into an error when using kp_winprob. The function worked as recently as early last month. Running the latest {hoopR} version (1.3).

**Error message:**

> Error: Problem with `mutate()` column `pd`. `pd = stringr::str_remove(.data$pd, "'Pd':")`. x Column `pd` not found in `.data`

**To Reproduce**
1. `library(hoopR)`
2. `kp_winprob(4316, 2019)` (or any mix of game and year)

**Comment by saiemgilani** [comment]
Fixed per #31 . Should be good to go with an additional return of runs
